version: "3.4"
services:
  api:
    image: ghcr.io/github-cloudlabsuser-087/fabrikam-api:latest
    ports:
      - "3001:3001"

  web:
    image: ghcr.io/github-cloudlabsuser-087/fabrikam-web:latest
    depends_on:
        - api
    environment:
        CONTENT_API_URL: http://api:3001
    ports:
        - "3000:80"
    